### ISSUE TITLE
Go to custom command definition / Custom command not found

### ISSUE THREAD

**Issue by gzliu36** [90poe/vscode-cy-helper#25]
**Describe the bug**
When I use "Cypress: Go to custom command definition" this message is displayed: "Custom command not found"

**Expected behavior**
I expected it to be forwarded to the custom command.

**Environment (please complete the following information):**
Extension version: 0.6.2
VS Code version: 1.45.1
OS: Linux (Mint):

** Prints **

![](https://files.gitter.im/vscode-cy-helper/community/0zmd/image.png)

![](https://files.gitter.im/vscode-cy-helper/community/piSk/image.png)

**Comment by Shelex** [comment]
@gzliu36 Thank you for posting an issue!
Quite weird as previously such kind of issue was already fixed for Linux Mint. Could you please check with latest version (v0.6.3) and let me know what is the more precise error message?

@canakg Thank you for comment. Great idea to add more accurate error messages.
Regarding your specific issue, `same (default) settings` - it mean that you will have `cypress/support` as default commands folder, but windows requires `cypress\support`. So same  config cannot be used for windows case. Have added possibility of reusing same config for different OS also. Could you please check v0.6.3 if it works for you?

**Comment by gzliu36** [comment]
Hi @Shelex,
I tried for v0.6.3 but still failed.
it shows "Definition location for command "create" not found at "c:\Users\user\Desktop\autotest\cypress\support""

and my folder structure is like this
![image](https://user-images.githubusercontent.com/32755495/84659059-68909280-af49-11ea-98a7-9034b43d667b.png)

**Comment by canakg** [comment]
Hey @Shelex , I changed the setting to `cypress\support` and I get the exact same error message as @gzliu36 

`Definition location for command "openSurvey" not found at "c:\git\e2e\cypress\support"`

![image](https://user-images.githubusercontent.com/62487376/84660871-7f060200-aee7-11ea-98f9-39776dd99837.png)

Index file is in `C:\git\e2e\cypress\support` as you can see here, imported from the child folders.

![image](https://user-images.githubusercontent.com/62487376/84660830-701f4f80-aee7-11ea-9dc9-30c008318c96.png)

![image](https://user-images.githubusercontent.com/62487376/84661197-ffc4fe00-aee7-11ea-8d85-4b38d683a6ae.png)

![image](https://user-images.githubusercontent.com/62487376/84661307-300c9c80-aee8-11ea-973a-c81542a11ebb.png)

**Comment by Shelex** [comment]
> Hi @Shelex,
> I tried for v0.6.3 but still failed.
> it shows "Definition location for command "create" not found at "c:\Users\user\Desktop\autotest\cypress\support""
> 
> and my folder structure is like this
> ![image](https://user-images.githubusercontent.com/32755495/84659059-68909280-af49-11ea-98a7-9034b43d667b.png)

Thank you for response. So, you have Windows, not Linux Mint OS. This clarifies a lot, hopefully will provide fix soon.

**Comment by Shelex** [comment]
@gzliu36 @canakg Please check version 0.6.4. Issue should be gone.

**Comment by canakg** [comment]
Yes <3 For me it is working now, thank you!

**Comment by gzliu36** [comment]
For me it is working too, thank you!
